### ISSUE TITLE
您好，最近拜读了您的网上银行项目，受益匪浅，但运行时有点问题想请教您

### ISSUE THREAD

**Issue by yinchunhui-ahu** [ZHUHAI-ICBC/Distributed-Systems#2]
前后端运行都成功，但是后端连接mycat-mysql数据库时出现"connection  time out"，而且仓库里提供的sql备份不全，您方便把全部表的SQL文件（如数据太大可以部分数据）发给我吗，我个人学习下，不做商业及其他用途，万分感谢~
                                                                                                                                                        Follower: Chunhui 
                                                                                                                                                        邮箱：yinchunhui.ahu@qq.com

**Comment by GeorgeeeLiu** [comment]
因为我们的阿里云到期了，所以连不上数据库啦，备份SQL文件已发你邮箱了
